/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.ProveedorData;
import Clases.Proveedor;
import javax.swing.JOptionPane;

/**
 *
 * @author solmedina
 */
public class ViewProveedor extends javax.swing.JInternalFrame {
    
    private ProveedorData proveedorData=new ProveedorData();
    
    public ViewProveedor() {
        initComponents();
        jbtnLimpiar.setEnabled(false);
        jbtnBaja.setEnabled(false);
        jtfEstado.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfDomicilio = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jtfEstado = new javax.swing.JTextField();
        jbtnGuardar = new javax.swing.JButton();
        JbtnModificar = new javax.swing.JButton();
        jbtnAlta = new javax.swing.JButton();
        jbtnBaja = new javax.swing.JButton();
        jbtnSalir = new javax.swing.JButton();
        jbtnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfIdProveedor = new javax.swing.JTextField();
        jbtnLimpiar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("PROVEEDOR");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("DOMICILIO");

        jLabel4.setText("TELEFONO");

        jLabel5.setText("ESTADO");

        jbtnGuardar.setText("GUARDAR");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        JbtnModificar.setText("MODIFICAR");
        JbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnModificarActionPerformed(evt);
            }
        });

        jbtnAlta.setText("ALTA");
        jbtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAltaActionPerformed(evt);
            }
        });

        jbtnBaja.setText("BAJA");
        jbtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBajaActionPerformed(evt);
            }
        });

        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jbtnBuscar.setText("BUSCAR");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jLabel6.setText("CODIGO");

        jbtnLimpiar.setText("LIMPIAR");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                    .addComponent(jtfTelefono)
                                    .addComponent(jtfNombre)
                                    .addComponent(jtfEstado)
                                    .addComponent(jtfIdProveedor))
                                .addGap(18, 18, 18)
                                .addComponent(jbtnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(JbtnModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnAlta)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnBaja)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnSalir)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnLimpiar)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuardar)
                    .addComponent(JbtnModificar)
                    .addComponent(jbtnAlta)
                    .addComponent(jbtnBaja)
                    .addComponent(jbtnSalir)
                    .addComponent(jbtnLimpiar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        // TODO add your handling code here:
        
         try
        {
            //Obtenemos los datos ingresados por el usuario
            String nombre = jtfNombre.getText();
            String domicilio = jtfDomicilio.getText();
            String telefono = jtfTelefono.getText();
            Boolean estado = true;
            try
            {

                long num = Long.parseLong(telefono);
                if (telefono.length() < 10 || telefono.length() > 15)
                {
                    JOptionPane.showMessageDialog(null, "El número ingresado no es correcto para un telefono válido.", "Error", JOptionPane.ERROR_MESSAGE);
                    jtfTelefono.setText(""); // Limpiar el campo JTextField
                    return;
                }
            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Ingrese un valor numérico válido para el telefono", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Proveedor proveedor = new Proveedor(nombre, domicilio, telefono, true);
            proveedorData.guardarProveedor(proveedor);
            
            jtfIdProveedor.setText(proveedor.getIdProveedor() + "");
            jbtnLimpiar.setEnabled(true);
            jbtnBaja.setEnabled(true);
            jtfIdProveedor.setEnabled(true);
            jtfEstado.setText("Activo");
            JOptionPane.showMessageDialog(this, "Proveedor añadido!", "¡ÉXITO!", JOptionPane.INFORMATION_MESSAGE);
 
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Datos invalidos, verifique su entrada " + ex.getMessage());
            jtfNombre.requestFocus();
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAltaActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(jtfIdProveedor.getText());
        proveedorData.altaProveedor(id);
        JOptionPane.showMessageDialog(this, "Proveedor dado de alta!", "¡ÉXITO!", JOptionPane.INFORMATION_MESSAGE);
        limpiar();

    }//GEN-LAST:event_jbtnAltaActionPerformed

    private void JbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnModificarActionPerformed
        //Obtenemos los datos ingresados por el usuario

        boolean estado;
        int id=Integer.parseInt(jtfIdProveedor.getText());
        String nombre = jtfNombre.getText();
        String domicilio = jtfDomicilio.getText();
        String telefono = jtfTelefono.getText();
        String estadoString = jtfEstado.getText();
        
        if(estadoString=="Activo"){
            estado=true;
        }else{
            estado=false;
        }
        try
        {
            long num = Long.parseLong(telefono);
            if (telefono.length() < 10 || telefono.length() > 15)
            {
                JOptionPane.showMessageDialog(null, "El número ingresado no es correcto para un telefono válido.", "Error", JOptionPane.ERROR_MESSAGE);
                jtfTelefono.setText(""); // Limpiar el campo JTextField
                return;
            }
        } catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Ingrese un valor numérico válido para el telefono", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Proveedor p = new Proveedor(id, nombre, domicilio, telefono, estado);
        proveedorData.modificarProveedor(p);
        JOptionPane.showMessageDialog(this, "Proveedor Modificado!", "¡ÉXITO!", JOptionPane.INFORMATION_MESSAGE);

        limpiar();
    }//GEN-LAST:event_JbtnModificarActionPerformed

    private void jbtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBajaActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(jtfIdProveedor.getText());
        proveedorData.bajaProveedor(id);
        JOptionPane.showMessageDialog(this, "Proveedor dado de baja!", "¡ÉXITO!", JOptionPane.INFORMATION_MESSAGE);
        limpiar();
    }//GEN-LAST:event_jbtnBajaActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
        String nombre = jtfNombre.getText();
        try{
            Proveedor p = new Proveedor();
            p=proveedorData.obtenerProveedorPorNombre(nombre);
//          
            jtfDomicilio.setText(p.getDomicilio());
            jtfTelefono.setText(p.getTelefono());
            if(p.isEstado()){
                jtfEstado.setText("Activo");
                jbtnAlta.setEnabled(false);
                jbtnBaja.setEnabled(true);
            }else{
                jtfEstado.setText("Inactivo");
                jbtnAlta.setEnabled(true);
                jbtnBaja.setEnabled(false);
            }
            jtfIdProveedor.setText(String.valueOf(p.getIdProveedor()));
            
       } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Datos invalidos, verifique el nombre " + ex.getMessage());
            jtfNombre.requestFocus();
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnAlta;
    private javax.swing.JButton jbtnBaja;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JTextField jtfDomicilio;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfIdProveedor;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables

private void limpiar(){
    jtfNombre.setText("");
    jtfDomicilio.setText("");
    jtfTelefono.setText("");
    jtfEstado.setText("");
    jtfIdProveedor.setText("");
}
}
