/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.*;
import Clases.*;
import javax.swing.JOptionPane;

public class ViewCliente extends javax.swing.JInternalFrame {

    private ClienteData clienteData = null;

    public ViewCliente() {
        initComponents();
        jtfIdCliente.setEditable(false);
        jtfEstado.setEditable(false);
        this.clienteData = new ClienteData();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtfIdCliente = new javax.swing.JTextField();
        jtfDni = new javax.swing.JTextField();
        jtfApellido = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfDomicilio = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jtfEstado = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jbtnBaja = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jcbEstado = new javax.swing.JCheckBox();
        jbtnSalir = new javax.swing.JButton();
        jbtnAlta = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("CLIENTES");

        jLabel2.setText("NRO. CLIENTE");

        jLabel3.setText("DNI");

        jLabel4.setText("APELLIDO");

        jLabel5.setText("NOMBRE");

        jLabel6.setText("DOMICILIO");

        jLabel7.setText("TELEFONO");

        jLabel8.setText("ESTADO");

        jtfIdCliente.setEditable(false);

        jbtnBuscar.setText("BUSCAR");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        jbtnGuardar.setText("GUARDAR");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        jbtnModificar.setText("MODIFICAR");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        jbtnBaja.setText("BAJA");
        jbtnBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBajaActionPerformed(evt);
            }
        });

        jbtnLimpiar.setText("LIMPIAR");
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jcbEstado.setText("Activo/Inactivo");

        jbtnSalir.setText("SALIR");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jbtnAlta.setText("ALTA");
        jbtnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jcbEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jbtnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jbtnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnAlta)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBaja)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnSalir)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnBuscar)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jcbEstado))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnGuardar)
                    .addComponent(jbtnModificar)
                    .addComponent(jbtnAlta)
                    .addComponent(jbtnBaja)
                    .addComponent(jbtnLimpiar)
                    .addComponent(jbtnSalir))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        
        try
        {

            String nombre = jtfNombre.getText();
            String apellido = jtfApellido.getText();
            String domicilio = jtfDomicilio.getText();
            String telefono = jtfTelefono.getText();
            Boolean estado = jcbEstado.isSelected();
            String dni;
            do{
             dni = jtfDni.getText();
             JOptionPane.showMessageDialog(null, "El número ingresado no es correcto para un dni válido.", "Error", JOptionPane.ERROR_MESSAGE);

            }while(dni.length()!=7||dni.length()!=8);
            try{
                int num = Integer.parseInt(dni);
                
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Ingrese un valor numérico valido para el DNI ", "Error", JOptionPane.ERROR_MESSAGE);
            }
            try{
                long num1=Long.parseLong(jtfTelefono.getText());
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Ingrese un valor numérico válido para el telefono", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            Cliente cliente = new Cliente(dni, apellido, nombre, domicilio, telefono, estado);
            clienteData.guardarCliente(cliente);
            jtfIdCliente.setText(cliente.getIdCliente() + "");
        
        } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Datos invalidos, verifique su entrada " + ex.getMessage());
            jtfDni.requestFocus();
        }
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed

            //Obtenemos los datos ingresados por el usuario
            String dni=jtfDni.getText();
            try{
                int num = Integer.parseInt(dni);
            } catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Debe  ingresar un numero valido para el DNI para poder modificar un cliente.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            try{
                int num1=Integer.parseInt(jtfTelefono.getText());
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Ingrese un valor numérico válido para el telefono", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            int id=Integer.parseInt(jtfIdCliente.getText());
            String nombre = jtfNombre.getText();
            String apellido = jtfApellido.getText();
            String dom=jtfDomicilio.getText();
            String tel=jtfTelefono.getText();
            Boolean estado = jcbEstado.isSelected(); 
            
            //Construye nuevo cliente y lo guarda en la BD

            Cliente c = new Cliente(id, dni, apellido, nombre, dom, tel, estado);
            clienteData.modificarCliente(c);
            limpiar();
            jtfIdCliente.setText("");
            jbtnBaja.setEnabled(true);
            jbtnGuardar.setEnabled(true);
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void jbtnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBajaActionPerformed
        // TODO add your handling code here:
            String dni=jtfDni.getText();
            try
            {
                int num = Integer.parseInt(dni);
            } catch (NumberFormatException e)
            {
                
                JOptionPane.showMessageDialog(null, "Debe  ingresar un numero valido para el DNI para poder modificar un cliente.", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
            jtfIdCliente.setEnabled(true);
            int id=Integer.parseInt(jtfIdCliente.getText());
            //public void bajaCliente(int id)
            //Cliente c = new Cliente();
            clienteData.bajaCliente(id);
            
            jbtnBaja.setEnabled(true);
            jbtnGuardar.setEnabled(true);
            jbtnLimpiar.setEnabled(true);
            jbtnModificar.setEnabled(true);
            limpiar();
    }//GEN-LAST:event_jbtnBajaActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
            jtfApellido.setText("");
            jtfNombre.setText("");
            jtfDni.setText("");
            jtfDomicilio.setText("");
            jtfTelefono.setText("");
            jtfEstado.setText("");
            jtfIdCliente.setText("");
            jtfDni.requestFocus();
            jbtnGuardar.setEnabled(true);
            jbtnBaja.setEnabled(true);
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
        try
        {
            String dni=jtfDni.getText();
            try
            {
                int num = Integer.parseInt(dni);
            } catch (NumberFormatException e)
            {
                
                JOptionPane.showMessageDialog(null, "Ingrese un valor numérico valido para el DNI.", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
            Cliente c = new Cliente();
            c=clienteData.obtenerClientePorDni(dni);
            jtfApellido.setText(c.getApellido());
            jtfNombre.setText(c.getNombre());
            jtfDni.setText(c.getDni());
            jtfDomicilio.setText(c.getDomicilio());
            jtfTelefono.setText(c.getTelefono());
            //jcbEstado.setSelected(c.isEstado());
            if(c.isEstado()){
                jtfEstado.setText("Activo");
                jbtnAlta.setEnabled(false);
                jbtnBaja.setEnabled(true);
            }else{
                jtfEstado.setText("Inactivo");
                jbtnAlta.setEnabled(true);
                jbtnBaja.setEnabled(false);
            }
            jtfIdCliente.setText(c.getIdCliente()+"");
            jtfIdCliente.setEnabled(false);
            jbtnLimpiar.setEnabled(true);
            jbtnModificar.setEnabled(true);
            jbtnGuardar.setEnabled(false);
            } catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Datos invalidos, verifique su entrada " + ex.getMessage());
            jtfDni.requestFocus();
        }
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAltaActionPerformed
        // TODO add your handling code here:
        String dni=jtfDni.getText();
            try
            {
                int num = Integer.parseInt(dni);
            } catch (NumberFormatException e)
            {
                
                JOptionPane.showMessageDialog(null, "Debe  ingresar un numero valido para el DNI para poder modificar un cliente.", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
            jtfIdCliente.setEnabled(true);
            int id=Integer.parseInt(jtfIdCliente.getText());
            //public void bajaCliente(int id)
            //Cliente c = new Cliente();
            clienteData.altaCliente(id);
            
            jbtnBaja.setEnabled(true);
            jbtnGuardar.setEnabled(true);
            jbtnLimpiar.setEnabled(true);
            jbtnModificar.setEnabled(true);
            limpiar();
    }//GEN-LAST:event_jbtnAltaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnAlta;
    private javax.swing.JButton jbtnBaja;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JCheckBox jcbEstado;
    private javax.swing.JTextField jtfApellido;
    private javax.swing.JTextField jtfDni;
    private javax.swing.JTextField jtfDomicilio;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfIdCliente;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        jtfApellido.setText("");
            jtfNombre.setText("");
            jtfDni.setText("");
            jtfDomicilio.setText("");
            jtfTelefono.setText("");
            jtfEstado.setText("");
            jtfIdCliente.setText("");
            jtfDni.requestFocus();
    }
}
